framework:
    secret: '%env(APP_SECRET)%'
    csrf_protection: true
    http_method_override: false
    handle_all_throwables: true
    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax
        storage_factory_id: session.storage.factory.native
    php_errors:
        log: true

    http_client:
        scoped_clients:
            twitch_authentication:
                base_uri: 'https://id.twitch.tv/oauth2/token'
                query:
                    client_id: '%env(TWITCH_CLIENT_ID)%'
                    client_secret: '%env(TWITCH_CLIENT_SECRET)%'
                    grant_type: 'client_credentials'
            igdb:
                base_uri: https://api.igdb.com/
                headers:
                    Client-ID: '%env(TWITCH_CLIENT_ID)%'

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
